export NAME="yuno-watch" # Name of the lib. Changing can be tricky, proceed with caution
export MYLIB_HOME="/usr/local/src/${USER}"
export CONF_D_DIR="${MYLIB_HOME}/conf.d/*.conf" # User custom configurations

export NGINX_LOGS="/var/log/nginx" # Folder where nginx writes logs
export LOG_OUTPUT="/var/log/${USER}" # Folder where this lib writes logs
export ROTATION_ROOT="/var/archive/${NAME}/"
export ROTATION_SUB="${ROTATION_ROOT}/og_nginx" # Place where original (compressed) logs will be saved to
export SUMMARY_ROOT="/var/cache/${NAME}/"
export SUMMARY_SUB="${SUMMARY_ROOT}/sum_nginx" # Place where summaries will be written to (note README.md/#Deletion)
export CONF="/etc/${NAME}"

export NGINX_LOG_FORMAT="default" # View conf.d/CONFIGURATION.md
export NGINX_ORIGINAL="access.log" # Original filename that nginx writes to
export ATTACK_LOG_OUTPUT="attacks.log"
export ALL_ATTACKS="${SUMMARY_ROOT}/attack_patterns.log"

export PERFORM_VISUAL_SUMMARY=true # Change to false if no Visual summaries with graphs should be created
export PERFORM_SUMMARY_ATTACK = true # Change to false

export DOCKER_VISUAL_PORT="5010" # Interal docker PORT that recieves the log summary in order to create graph
export DOCKER_EXTERNAL_VISUAL_PORT="127.0.0.1:5010" # PORT to request a summary to

export SUMMARIZING_BACK=1 # Called daily by the scripts. Determines how many days ago the file taken to be summarized was. (1 => log from yesterday)
export KEEP_OG_LOGS_FOR=6 # Amount of time in months, for which original logs will be kept

export WHICH_ALL_ACTIONS="new-folder,rotate-nginx,perform-summary,merge-attacks-patterns,compress-og,auto-detele" # Determines which actions to active when yuno-watch activate all-actions is called