export NAME="yuno-watch" # Name of the lib. Changing can be cause some scripts to fail. Proceed with caution
export BASE_DIR="/usr/local/src/${NAME}"

export NGINX_LOGS="/var/log/nginx" # Folder where nginx writes logs
export LOG_OUTPUT="/var/log/${NAME}" # Folder where this lib writes logs
export ROTATION_ROOT="/var/archive/${NAME}"
export ROTATION_SUB="${ROTATION_ROOT}/og_nginx" # Place where original (compressed) logs will be saved to
export ROTATION_TO_BE_IMPORTED="${ROTATION_ROOT}/to_import_nginx" # Place for users to put original logs, all accummulated by just the month. Will be imported by yuno-watch perform import --month <YY-mm>
export SUMMARY_ROOT="/var/cache/${NAME}"
export SUMMARY_SUB="${SUMMARY_ROOT}/sum_nginx" # Place where summaries will be written to (note README.md/#Deletion)
export CONF="/etc/${NAME}"

export NGINX_LOG_FORMAT="default" # View CONFIGURATION.md
export NGINX_ORIGINAL="access.log" # Original filename that nginx writes to
export ATTACK_LOG_OUTPUT="attacks.log"
export ALL_ATTACKS="${SUMMARY_ROOT}/attack_patterns.log"

export PERFORM_BASIC_SUMMARY=true # Change to false if no 'normal' summary should be created. This is the main summary also used by PERFORM_VISUAL_SUMMARY, but might be wanted to be set to false on certain perform commands
export PERFORM_VISUAL_SUMMARY=true # Change to false if no Visual summaries with graphs should be created
export PERFORM_SUMMARY_ATTACK=true # Change to false if no summary for attack patterns should be created
export INTERVAL_VISUAL_SUMMARY="daily" # Can also be changed to 'monthly' or 'yearly' so that the visual summary is performed less often

export DOCKER_VISUAL_PORT="5010" # Interal docker PORT that recieves the log summary in order to create graph
export DOCKER_EXTERNAL_VISUAL_PORT="127.0.0.1:5010" # PORT to request a summary to

export SUMMARIZING_BACK=1 # Called daily by the scripts. Determines how many days ago the file taken to be summarized was. (1 => log from yesterday)
export KEEP_OG_LOGS_FOR=6 # Amount of time in months, for which original logs will be kept

export WHICH_ALL_ACTIONS="new-folder,rotate-nginx,perform-summary,merge-attacks-patterns,compress-og,auto-detele" # Determines which actions to active when yuno-watch activate all-actions is called