#!/bin/bash
# Make a copy of a Nginx file from ROTATION_TO_BE_IMPORTED to the directory used by this package.

set -euo pipefail
umask 077

YEAR="$1"
MONTH="$2"
DAY="$3"

YEAR_MONTH="$YEAR-$MONTH"
FULL_ROOT_PATH="$ROTATION_SUB/$YEAR_MONTH/$DAY"
FULL_SUM_PATH="$SUMMARY_SUB/$YEAR_MONTH/$DAY"
YMD="$YEAR$MONTH$DAY"

shopt -s nullglob
FILE="$ROTATION_TO_BE_IMPORTED/$YEAR_MONTH/$NGINX_ORIGINAL_FILENAME-$YMD"

mkdir -p $FULL_ROOT_PATH $FULL_SUM_PATH
chown $NAME:$NAME $FULL_ROOT_PATH $FULL_SUM_PATH
cp $FILE $FULL_ROOT_PATH/$NGINX_ORIGINAL_FILENAME-$YMD
chown "$NAME:$NAME" "$FULL_ROOT_PATH/$NGINX_ORIGINAL_FILENAME-$YMD"
