name: Setup

on:
  push:
    branches: [ main ]

jobs:
  alma-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build AlmaLinux container
      run: docker compose -f docker-compose.test.yml build

    - name: Run Almalinux Container and test everything
      run: docker compose -f docker-compose.test.yml run --rm yuno-watch

    - name: Tear down
      if: always()
      run: docker compose down
